### PR TITLE
Updated Locale

### PR DESCRIPTION
**Pull request by FrankieMa77**
---
name: Alexei Magonov
about: Use this template when making a pull request for a bug or feature for TabMerger.
title: "Adding Belorussian localization. Fixing Russian localization"
assignees: lbragile
---

# Description

Added **BY** (Belarussian) locale
Fixed  **RU** locale
I have checked the auto-translated Russian localization file for readability, correctness, and compliance to the original meaning of the text. Several misreadings were corrected for adequate translation. 

I have also added ```/public/locale/by``` folder and created a ```messages.json``` file using the existing pattern. This  addition provides translation to the Belorussian language to  increase application popularity and accessibility in Belarus. 

## Type of change

- [x] New feature/enhancement (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Both localizations were run through a proofreading service. 

**Test Configuration**:

* OS: (e.g. Windows)
* Browser: (Chrome, Firefox, Edge)
* Version: (e.g. v1.4.3)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lbragile** [comment]
Hi @FrankieMa77,

Please fill out the PR template provided above and I will have a look at your submission.

**Comment by FrankieMa77** [comment]
Form is filled to the best of my knowledge.

**Comment by lbragile** [comment]
@FrankieMa77 I edited your PR message so that it is more clear, did not notice your comments at first - sorry.

> I have also added /public/locale/by folder and created a messages.json file using the existing pattern. This addition provides translation to the Belorussian language to increase application popularity and accessibility in Belarus.

Is this locale supported? List of supported locales: https://developer.chrome.com/docs/webstore/i18n/

> Both localizations were run through a proofreading service.

Which service? Please provide all the necessary information.

> Test Configuration:
> 
> - OS: (e.g. Windows)
> - Browser: (Chrome, Firefox, Edge)
> - Version: (e.g. v1.4.3)

Indicated these so that I know your specific implementation details.

Please also go through the final checklist and make sure all steps are taken.

As a final note, although I appreciate your effort, you should first create an ```issue``` before making a pull request. 
I was under the impression that you plan to translate the [settings page](https://github.com/lbragile/TabMerger/projects/1#card-51996997) into Russian and was hoping to see how you do so. As a person who also understands Russian, I could see if the translation was adequate.

I think pull requests should include code changes that add/fix features rather than simply adjust text, but I could be wrong.

To be clear, I really appreciate your effort, just want to make sure that contributions follow some set standard.

Let me know what you think.

**Comment by lbragile** [comment]
No response to my above comment for three weeks now. Will close this PR and can re-open if a valid response is given. Thank you!

**Review by lbragile — COMMENTED** [review]
Is BY locale supported? List of supported locales: https://developer.chrome.com/docs/webstore/i18n/

See my [reply](https://github.com/lbragile/TabMerger/pull/9#issuecomment-758206634) for more details.

**Pull request closed without merging**
